footprint:
  [
    [0.154, 0.14],
    [0.154, -0.14],
    [-0.03, -0.14],
    [-0.1, -0.1],
    [-0.15, 0],
    [-0.1, 0.1],
    [-0.03, 0.14],
  ]

# Set the tolerance for tf transforms
transform_tolerance: 0.2

# Obstacle marking parameters
obstacle_range: 2.5
raytrace_range: 3.0

# Cost function parameters
obstacle_layer: 
  observation_sources: scan
  enable: true
  track_unknown_space: true
  footprint_clearing_enabled: true
  scan: {
        data_type: LaserScan, 
        expected_update_rate: 0.4,
        observation_persistence: 0.0,
        marking: true, 
        clearing: true,
        topic: /scan
  }
