global_costmap:
  global_frame: map
  robot_base_frame: base_link_fusion
  update_frequency: 5.0
  publish_frequency: 0.5
  inflation_radius: 0.6
  static_map: true

  rolling_window: false
  # obstacle_layer: 
  #   observation_sources: scan
  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  # - {name: costmap_prohibition_layer,   type: "costmap_prohibition_layer_namespace::CostmapProhibitionLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
